# version: '3.8'
# services:
#   app:
#     build: .
#     ports:
#       - "4000:4000"
#     environment:
#       DB_HOST: db
#       DB_USER: root
#       DB_PASSWORD: secret
#       DB_NAME: task_management
#     depends_on:
#       - db
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: task_management
#     ports:
#       - "3306:3306"


      version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=task_management
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=task_management
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d # Auto-run SQL scripts
    ports:
      - "3306:3306"